// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5293.subsystems;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc5293.Robot;
import org.usfirst.frc5293.RobotMap;
import org.usfirst.frc5293.commands.MecanumDrive;

public class Drivetrain extends Subsystem {

    private final RobotDrive drive = RobotMap.Drivetrain.control;

    public void initDefaultCommand() {
        setDefaultCommand(new MecanumDrive());
    }

    public void drive() {
    	double x = Robot.oi.getJoystick1().getX();
    	double y = Robot.oi.getJoystick1().getY();
    	double r = Robot.oi.getJoystick1().getTwist();

        drive.mecanumDrive_Cartesian(x, y, r, 0);
    }

    public void autondrive(double xstrafe, double ystrafe, double rrotation) {
    	drive.mecanumDrive_Cartesian(xstrafe, ystrafe, rrotation, 0);
    }

    public void stop() {
    	drive.mecanumDrive_Cartesian(0, 0, 0, 0);
    }
}

