// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5293.subsystems;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc5293.Devices;
import org.usfirst.frc5293.Prefs;
import org.usfirst.frc5293.commands.teleop.control.ShooterControl;

public class Shooter extends Subsystem {

    private final SpeedController master = Devices.getShooter().getController();

    public void initDefaultCommand() {
        setDefaultCommand(new ShooterControl());
    }

    public void setPower(double x) {
        SmartDashboard.putNumber("Shooter Power", x);
        master.set(x);
    }

    public void stop() {
        setPower(0);
    }

//    private Double getSpeed() {
//        return Prefs.getToteElevator().getSpeed().get();
//    }
}

