// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5293.subsystems

import edu.wpi.first.wpilibj.command.Subsystem
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard
import org.usfirst.frc5293.Devices
import org.usfirst.frc5293.commands.teleop.control.ShooterControl

class Shooter : Subsystem() {

    private val controller = Devices.shooter.controller

    public override fun initDefaultCommand() {
        defaultCommand = ShooterControl()
    }

    var power: Double
        get() = controller.get()
        set(x) {
            SmartDashboard.putNumber("Shooter Power", x)
            controller.set(x)
        }

    fun stop() {
        power = 0.0
    }
}

