// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5293.subsystems;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc5293.Devices;
import org.usfirst.frc5293.Prefs;
import org.usfirst.frc5293.commands.teleop.control.ToteElevatorControl;

public class ToteElevator extends Subsystem {

    private final DigitalInput bottomLimitSwitch = Devices.getToteElevator().getBottomLimitSwitch();
    private final SpeedController master = Devices.getToteElevator().getController();

    public void initDefaultCommand() {
        setDefaultCommand(new ToteElevatorControl());
    }

    public void raise(double percentage) {
    	setPower(percentage * -getSpeed());
    }

    public void lower(double percentage) {
        // TODO: Re-enable this once we get the bottom limit switch implemented
//        if (bottomLimitSwitch.get()) {
//            stop();
//            return;
//        }
    	setPower(percentage * getSpeed());
    }

    private void setPower(double value) {
        if (master instanceof CANTalon && Prefs.getToteElevator().getIsVoltageRampEnabled().get()) {
            ((CANTalon) master).setVoltageRampRate(Prefs.getToteElevator().getVoltageRamp().get());
        }

        master.set(value);
        // SmartDashboard.putNumber("tote_elevator:last_power", value);
    }

    public void stop() {
    	master.set(0);
    }

    private Double getSpeed() {
        return Prefs.getToteElevator().getSpeed().get();
    }
}

