// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5293.subsystems;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc5293.RobotMap;

public class ToteElevator extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    SpeedController talonSRX4 = RobotMap.toteElevatorTalonSRX4;
    SpeedController talonSRX5 = RobotMap.toteElevatorTalonSRX5;
    DigitalInput limitTote0 = RobotMap.toteElevatorLimitTote0;
    DigitalInput limitToteElev1 = RobotMap.toteElevatorLimitToteElev1;
    DigitalInput limitToteElev2 = RobotMap.toteElevatorLimitToteElev2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public DigitalInput getUpperSwitch () {
    	return limitToteElev1;
    }
    public DigitalInput getLowerSwitch () { //DIGITAL INPUT TYPE NEEDS TO BE FIXED
    	return limitToteElev2;
    }

    public void raiseTotes(){
    	talonSRX4.set(1); //ADJUST THESE SPEEDS
    	talonSRX5.set(1); //ADJUST THESE SPEEDS
    }

    public void lowerTotes(){
    	talonSRX4.set(-0.6); //ADJUST THESE SPEEDS
    	talonSRX5.set(-0.6); //ADJUST THESE SPEEDS
    }

    public void stop() {
    	talonSRX4.set(0);
    	talonSRX5.set(0);
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

